name: ai_webscraper
description: A comprehensive AI-powered web scraper for Dart with OpenAI and Google Gemini integration, featuring a Flutter web dashboard
version: 0.1.1
homepage: https://github.com/SamsonTobi/ai_webscraper
repository: https://github.com/SamsonTobi/ai_webscraper
issue_tracker: https://github.com/SamsonTobi/ai_webscraper/issues
documentation: https://pub.dev/documentation/ai_webscraper/latest/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Core AI WebScraper dependencies
  http: ^1.4.0
  html: ^0.15.6
  meta: ^1.17.0
  puppeteer: ^3.19.0
  google_generative_ai: ^0.4.7
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
